OrdererOrgs:
  - Name: Orderer
    Domain: oculus.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Register1
    Domain: register1.oculus.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Customer
    Domain: customer.oculus.com
    Template:
      Count: 2
    Users:
      Count: 1
